@educonnect_HostAddress = http://localhost:5098

### Healthcheck
GET {{educonnect_HostAddress}}/health
Accept: application/json

### Create user
POST {{educonnect_HostAddress}}/users
Content-Type: application/json
Accept: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@example.com"
}
